<?php

namespace ASA\ChampionnatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends EntityRepository {

    public function getTeamAndMatchs() {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin("a.matchs", 'm');
        
        return $qb->getQuery()->getResult();
    }
}
