<?php

namespace ASA\ChampionnatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository {

    public function getNextEvenements($date) {
        $qb = $this->createQueryBuilder('a')
                ->where('a.date >= :date')
                ->setParameter('date', $date->format('Y-m-d'));


        return $qb->getQuery()->getResult();
    }

}
