<?php

namespace ASA\ChampionnatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsRepository extends EntityRepository
{  
    public function getMatchsByTeam($slug){
        $qb = $this->createQueryBuilder('m')
            ->leftJoin("m.equipe", "t")
                ->where("t.slug = :slug")
                ->setParameter("slug", $slug)
                ->orderBy("m.date");
                
        return $qb->getQuery()->getResult();
    }

}
