<?php

namespace ASA\ChampionnatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository {

    public function getNewsHome() {

        $qb = $this->createQueryBuilder('a');

        $qb->orderBy('a.date', 'DESC');
        $qb->setMaxResults(2);
        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function getNextNew($slug) {
        $id = $this->findOneBySlug($slug);
        $id = $id->getId();

        $qb = $this->createQueryBuilder('a')
                ->select("a.slug")
                ->where("a.id > $id");

        return $qb->getQuery()->getArrayResult();
    }

    public function getPrevNew($slug) {
        $id = $this->findOneBySlug($slug);
        $id = $id->getId();

        $qb = $this->createQueryBuilder('a')
                ->select("a.slug")
                ->where("a.id < $id");

        return $qb->getQuery()->getArrayResult();
    }

}
